version: 0.0
resources:
  - name: backend-repo
    type: AWS::ECS::TaskDefinition
    properties:
      taskDefinition: Backend_pipline_task
      image: 242927478162.dkr.ecr.us-east-1.amazonaws.com/backend-repo/242927478162.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest
