version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build docker image
        run: docker build -t kingzzo/nodejs-app .
      - name: Publish image to docker hub
        run: docker push kingzzo/nodejs-app:latest

artifacts:
  files: '**/*'
