version: 0.2

phases:
  install:
    runtime-versions:
      docker: latest

  build:
    commands:
     
      - run: docker login -u kingzzo  -p Kingzzo 
      - run: docker build -t kingzzo/nodejs-app .
      - run: docker push kingzzo/nodejs-app:latest

artifacts:
  files: '**/*'  
