version: 0.2

phases:
  install:
    runtime-versions:
      docker: latest

  build:
    commands:
      - echo "Build phase: This is where you can put your build commands."
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD  # Set the environment variables in your CodeBuild project
      - docker build -t kingzzo/nodejs-app .
      - docker push kingzzo/nodejs-app:latest

artifacts:
  files: '**/*'  
