get https://backend2.gridxmeter.com/finance/currentYearRevenue
Content-Type: application/json

####
get https://backend2.gridxmeter.com/finance/currentMonthRevenue
Content-Type: application/json

####
get https://backend2.gridxmeter.com/finance/currentYearRevenue
Content-Type: application/json

####
get http://localhost:4000/finance/currentAndLastYearMonthRevenueTotal
Content-Type: application/json

###
get http://localhost:4000/finance/currentAndLastWeek
Content-Type: application/json

####