get https://backend2.gridxmeter.com/finance/time-periods
Content-Type: application/json

####
get https://backend2.gridxmeter.com/finance/currentAndLastYearMonthRevenueTotal 
Content-Type: application/json

###
get https://backend2.gridxmeter.com/finance/currentAndLastWeek
Content-Type: application/json

####