

get http://localhost:4000/profile/1

###
get http://localhost:4000/allAdmins
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBY2Nlc3NMZXZlbCI6IjEiLCJpYXQiOjE3MDY1MTI2NDgsImV4cCI6MTcwNjUxNjI0OH0.hFqOblwcBzblS23Tw_e_-kueKQ8jpudOCF2dCWDQdBk
Content-Type: application/json
###

post http://localhost:4000/UserUpdate/1

{
"FirstName":"Update update",
"Email":"etangoking90@gmail.com"

}
###

post http://localhost:4000/AdminUpdate/1

###
delete http://localhost:4000/deleteUser/3

Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOjMwLCJBY2Nlc3NMZXZlbCI6MSwiaWF0IjoxNjk3MDM4ODkzfQ.ib2Gbym7p6iC_p5gSdY3lNarXeyzsnX_8dWvoMUZbRA
Content-Type: application/jsonn



