###
get http://localhost:4000/meter_change
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTE3NDM5NSwiZXhwIjoxNzE1MTc3OTk1fQ.kaVG3URU_cHRlvT_n-k5hat5gX_DS5i8g2JFz6_6UUs
###
get http://localhost:4000/active_state_count
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTE3NDM5NSwiZXhwIjoxNzE1MTc3OTk1fQ.kaVG3URU_cHRlvT_n-k5hat5gX_DS5i8g2JFz6_6UUs
###
get http://localhost:4000/inactive_state_count
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTE3NDM5NSwiZXhwIjoxNzE1MTc3OTk1fQ.kaVG3URU_cHRlvT_n-k5hat5gX_DS5i8g2JFz6_6UUs
###
get http://localhost:4000/powerIncreaseOrDecrease 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTYwMTI1NSwiZXhwIjoxNzE1NjA0ODU1fQ.71rQ83BM2PnSCUyoq7QnhoOZlYxOyoGIa-BRbCVeys4
###
post http://localhost:4000/suburbAdvancedPowerIncreaseOrDecrease
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTYwMTI1NSwiZXhwIjoxNzE1NjA0ODU1fQ.71rQ83BM2PnSCUyoq7QnhoOZlYxOyoGIa-BRbCVeys4

{
    "suburbs":[
     "Academia" 
    ]
}

###
get http://localhost:4000/ratioUnitsBoughtAndUsedThisMonth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDk4MTg1MywiZXhwIjoxNzE0OTg1NDUzfQ.0YY4v7Ve7p9E378Za94p0g4YOlJ-zjaC1-T2lLr4N_w
### 
get http://localhost:4000/time-periods-ratios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTYwMTI1NSwiZXhwIjoxNzE1NjA0ODU1fQ.71rQ83BM2PnSCUyoq7QnhoOZlYxOyoGIa-BRbCVeys4
###
get http://localhost:4000/WeekRatio 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTYwMTI1NSwiZXhwIjoxNzE1NjA0ODU1fQ.71rQ83BM2PnSCUyoq7QnhoOZlYxOyoGIa-BRbCVeys4
###
get http://localhost:4000/monthRatios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTYwMTI1NSwiZXhwIjoxNzE1NjA0ODU1fQ.71rQ83BM2PnSCUyoq7QnhoOZlYxOyoGIa-BRbCVeys4

###
POST http://localhost:4000/suburbRevenueIncreaseOrDecrease
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTE4NDUwNSwiZXhwIjoxNzE1MTg4MTA1fQ.Zr2LzSapWyMvCbyBr0IBdNgyYryEKDT0gNnS5xS9je4


{
    "suburbs":[
     "Academia" 
    ]
}