DELETE https://backend2.gridxmeter.com/deleteNotifications/41322
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBY2Nlc3NMZXZlbCI6IjEiLCJpYXQiOjE3MDkyMDU0NjIsImV4cCI6MTcwOTIwOTA2Mn0.nKyNLrSGFG6y36H3KwjOnaQIDaEqt7k2r-quQlVhIX8
Content-Type: application/json

####

get http://localhost:4000/notificationsByDRN0260066545641
Content-Type: application/json
###
get https://backend2.gridxmeter.com/criticalNotifications
Content-Type: application/json

###
get http://localhost:4000/getAll
Content-Type: application/json