DELETE https://backend2.gridxmeter.com/deleteNotifications/25
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBY2Nlc3NMZXZlbCI6IjEiLCJpYXQiOjE3MDgwNzM1NDYsImV4cCI6MTcwODA3NzE0Nn0.aNlEckwLQxxznVi-yf7Wdgqog4577O_qVG7aURXktvg
Content-Type: application/json

####

get http://localhost:4000/notificationsByDRN/0260066545641
Content-Type: application/json
###
get http://localhost:4000/criticalNotifications
Content-Type: application/json