
get http://localhost:4000/allProcessedTokensByDRN/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcyNDE0MTA5MCwiZXhwIjoxNzI0MTQ0NjkwfQ.wNTKsAZ_ZXx_46XugNw-dFCbyYUofTHxrPrmriay9j8
###
get http://localhost:4000/meterDataByDRN0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTE4MjE0MCwiZXhwIjoxNzE1MTg1NzQwfQ.dIr96hdHY0j0GkoIu-Cw0oD2jXltphVvp9WuqFxsSZg
###
GET http://localhost:4000/meterWeekAndMonthData/0260066545641 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcyNDE0MTA5MCwiZXhwIjoxNzI0MTQ0NjkwfQ.wNTKsAZ_ZXx_46XugNw-dFCbyYUofTHxrPrmriay9j8
###
get http://localhost:4000/notificationsTypesByDRN/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxMzg3MzUyMiwiZXhwIjoxNzEzODc3MTIyfQ.56wMXXfSoqxjWaTX5IXNhCdkx80XIXvXB4FOV3krukA