get https://backend2.gridxmeter.com/allProcessedTokensByDRN0260152877924
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxMzg3MzUyMiwiZXhwIjoxNzEzODc3MTIyfQ.56wMXXfSoqxjWaTX5IXNhCdkx80XIXvXB4FOV3krukA
###
get https://backend2.gridxmeter.com/meterDataByDRN0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxMzg3MzUyMiwiZXhwIjoxNzEzODc3MTIyfQ.56wMXXfSoqxjWaTX5IXNhCdkx80XIXvXB4FOV3krukA
###
GET http://localhost:4000/meterWeekAndMonthData0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDQyMDUxMSwiZXhwIjoxNzE0NDI0MTExfQ.GuAqQLcA_gI0BnFjz47bE2xCXSvEqXjYBbFCJSwOZp8
###
get http://localhost:4000/notificationsTypesByDRN/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxMzg3MzUyMiwiZXhwIjoxNzEzODc3MTIyfQ.56wMXXfSoqxjWaTX5IXNhCdkx80XIXvXB4FOV3krukA