###
get http://localhost:4000/meter_change
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTE3NDM5NSwiZXhwIjoxNzE1MTc3OTk1fQ.kaVG3URU_cHRlvT_n-k5hat5gX_DS5i8g2JFz6_6UUs
###
get http://localhost:4000/active_state_count
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcyMDk3OTMzMiwiZXhwIjoxNzIwOTgyOTMyfQ.55A_MteXBh4u4St23jANt2wZ0lyfGBFoJWXN_7n1tS8
###
get http://localhost:4000/inactive_state_count
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcyMDk3OTMzMiwiZXhwIjoxNzIwOTgyOTMyfQ.55A_MteXBh4u4St23jANt2wZ0lyfGBFoJWXN_7n1tS8
###
get http://localhost:4000/powerIncreaseOrDecrease 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcyMDk3OTMzMiwiZXhwIjoxNzIwOTgyOTMyfQ.55A_MteXBh4u4St23jANt2wZ0lyfGBFoJWXN_7n1tS8
###
post http://localhost:4000/suburbAdvancedPowerIncreaseOrDecrease
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcyMDk3OTMzMiwiZXhwIjoxNzIwOTgyOTMyfQ.55A_MteXBh4u4St23jANt2wZ0lyfGBFoJWXN_7n1tS8

{
    "suburbs":[
     "Academia" 
    ]
}

###
get http://localhost:4000/ratioUnitsBoughtAndUsedThisMonth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTc2NTU5NiwiZXhwIjoxNzE1NzY5MTk2fQ.-tpSjXM699kxrmLJXu5elBlBxTdsrwat5MG5AELi0FA
### 
get http://localhost:4000/time-periods-ratios 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTc3ODI0NiwiZXhwIjoxNzE1NzgxODQ2fQ.g7FBTvttyJznvfaRz8GJr6Q61IgH4lveeYxNzZZObQI
###
get http://localhost:4000/WeekRatio 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTc3ODI0NiwiZXhwIjoxNzE1NzgxODQ2fQ.g7FBTvttyJznvfaRz8GJr6Q61IgH4lveeYxNzZZObQI
###
get http://localhost:4000/monthRatios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcyMDY5ODEyOCwiZXhwIjoxNzIwNzAxNzI4fQ.4SZ4rqJOEjWoD3az34EGdRE6Wxix0C5IuPzjf2OCEsM

###
POST http://localhost:4000/suburbRevenueIncreaseOrDecrease
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcyMDk3OTMzMiwiZXhwIjoxNzIwOTgyOTMyfQ.55A_MteXBh4u4St23jANt2wZ0lyfGBFoJWXN_7n1tS8
  

{
    "suburbs":[
     "Academia" 
    ]
}