post http://localhost:4000/energy0260152877924

Content-Type: application/json

# {
#     "DRN":"0000039967351"
# }

###
post http://localhost:4000/currentAndLastWeekEnergy0260152877924
Content-Type: application/json

# {
#     "DRN":"0000039967351"
# }
####
post http://localhost:4000/CurrentDayEnergy0260152877924
Content-Type: application/json

# {
#     "DRN":"0000039967351"
# }
###

get http://localhost:4000/activeInactiveMeters
Content-Type: application/json

###
post http://localhost:4000/tokenAmount
Content-Type: application/json