
get http://localhost:4000/allProcessedTokensByDRN0260066545641
Content-Type: application/json
###
get https://localhost:4000/meterDataByDRN0260066545641
Content-Type: application/json
###
###--------------PotentialIssue-----------####
get http://localhost:4000/meterWeekAndMonthData0260066545641
Content-Type: application/json
###
get http://localhost:4000/activeInactiveMeters
Content-Type: application/json
###
get http://localhost:4000/tokenAmount
Content-Type: application/json
###
get http://localhost:4000/totalTokensBought
Content-Type: application/json
###
get http://localhost:4000/totalEnergyAmount
Content-Type: application/json
###
get http://localhost:4000/weeklyDataAmount
Content-Type: application/json
###
get http://localhost:4000/currentDayEnergy
Content-Type: application/json
###
post http://backend2.gridxmeter.com/insertMeterData
Content-Type: application/json

{
 "data":[
     "DRN": "0260694812784",
    "Surname": "Jose",
    "Name": "Dino",
    "Suburb": "Havana",
    "City": "Wndhoek",
    "Streetname": "Tugela Steet",
    "Housenumber": "20",
    "Simnumber": "0811234567",
    "Usercategory": "Home",
    "Meterlng": "-22.521021538121",
    "Meterlat": "17.0324874862621",
    "Transformerlng": "-22.5208258027464",
    "Transformerlat": "17.033259962460",
    "TransformerDRN": "0260000000090"
 ]
}
###

post http://localhost:4000/getSuburbEnergy
Content-Type: application/json

{
    "suburbs":[
     "Academia" ,
      "Auasblick" ,
      "Avis" ,
     "Cimbebasia" ,
      "Dorado Park" ,
      "Donkerhoek" ,
     "Elisenheim" ,
      "Eros" ,
     "Eros Park" ,
     "Freedom Land" ,
     "Goreangab" ,
      "Groot Aub" ,
      "Greenwell" ,
     "Hakahana" ,
      "Havana" ,
       "Hochland Park" ,
       "Katutura" ,
       "Khomasdal" ,
     "Kleine Kuppe" ,
      "Klein Windhoek" ,
     "Lafrenz" ,
       "Ludwigsdorf" ,
       "Luxury Hill" ,
       "Maxuilili" ,
        "Northern Industrial " ,
       "Okuryangava" ,
        "Olympia" ,
       "Ombili" ,
       "Otjomuise" ,
       "Pionierspark" ,
        "Prosperita" ,
      "Rocky Crest" ,
     "Southern Industria" ,
      "Suiderhof" ,
     "Tauben Glen" ,
      "Wanaheda" ,
        "Windhoek Central" ,
        "Windhoek North" ,
       "Windhoek West" 
    ]}
  
###
get http://backend2.gridxmeter.com/meter_change
Content-Type: application/json
###
get http://backend2.gridxmeter.com/active_state_count
Content-Type: application/json
###
get http://backend2.gridxmeter.com/inactive_state_count
Content-Type: application/json
###
post http://localhost:4000/insertTransformer
Content-Type: application/json
 
{
  "TransformerData":{
    "DRN":"0240000000009",
    "LocationName":"Khomasdal",
    "Name":"Tugena 4",
    "Type":"Big Tranformer",
    "pLat":"-22.538236805338208",
    "pLng":"17.050350565314446",
    "Status":"1",
    "PowerSupply":"0260000000003",
    "powerRating":"1000kVA",
    "city":"Windhoek"
  }
}

###
get http://localhost:4000/active-energy
Content-Type: application/json


####
get http://localhost:4000/gridTopology
Content-Type: application/json

{
  "cities":[
    "Windhoek",
    "Swakopmund",
    "Walvis Bay",
    "Rehoboth"
  ]
}
