get http://localhost:4000/meterProfile/meterResetHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTU4MzcwMCwiZXhwIjoxNzE1NTg3MzAwfQ.fWV8COYbHKcpHsBX8k2UebI8I6CpiXDffUgSku4pP5w
###
get http://localhost:4000/meterProfile/meterCalibrationHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTU4MzcwMCwiZXhwIjoxNzE1NTg3MzAwfQ.fWV8COYbHKcpHsBX8k2UebI8I6CpiXDffUgSku4pP5w
###
get http://localhost:4000/meterProfile/meterControlHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTU4MzcwMCwiZXhwIjoxNzE1NTg3MzAwfQ.fWV8COYbHKcpHsBX8k2UebI8I6CpiXDffUgSku4pP5w
###
get http://localhost:4000/meterProfile/meterStateHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTU4MzcwMCwiZXhwIjoxNzE1NTg3MzAwfQ.fWV8COYbHKcpHsBX8k2UebI8I6CpiXDffUgSku4pP5w
###
get http://localhost:4000/meterProfile/heaterControlHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTU4MzcwMCwiZXhwIjoxNzE1NTg3MzAwfQ.fWV8COYbHKcpHsBX8k2UebI8I6CpiXDffUgSku4pP5w
###
get http://localhost:4000/meterProfile/heaterStateHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTU4MzcwMCwiZXhwIjoxNzE1NTg3MzAwfQ.fWV8COYbHKcpHsBX8k2UebI8I6CpiXDffUgSku4pP5w
###
get http://localhost:4000/meterProfile/stsTokenHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTU4MzcwMCwiZXhwIjoxNzE1NTg3MzAwfQ.fWV8COYbHKcpHsBX8k2UebI8I6CpiXDffUgSku4pP5w
###
get http://localhost:4000/meterProfile/tokenInformation/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTU4MzcwMCwiZXhwIjoxNzE1NTg3MzAwfQ.fWV8COYbHKcpHsBX8k2UebI8I6CpiXDffUgSku4pP5w