get http://localhost:4000/settings/meterResetHistory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDM3NzMwOCwiZXhwIjoxNzE0MzgwOTA4fQ.Vk9IozjS0fYz13LiE1PX2odbtW0FWAkqJzwR1TYiK6I
###
get http://localhost:4000/settings/meterCalibrationHistory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDM3NzMwOCwiZXhwIjoxNzE0MzgwOTA4fQ.Vk9IozjS0fYz13LiE1PX2odbtW0FWAkqJzwR1TYiK6I
###
get http://localhost:4000/settings/meterControlHistory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDM3NzMwOCwiZXhwIjoxNzE0MzgwOTA4fQ.Vk9IozjS0fYz13LiE1PX2odbtW0FWAkqJzwR1TYiK6I
###
get http://localhost:4000/settings/meterStateHistory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDM3NzMwOCwiZXhwIjoxNzE0MzgwOTA4fQ.Vk9IozjS0fYz13LiE1PX2odbtW0FWAkqJzwR1TYiK6I
###
get http://localhost:4000/settings/heaterControlHistory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDM3NzMwOCwiZXhwIjoxNzE0MzgwOTA4fQ.Vk9IozjS0fYz13LiE1PX2odbtW0FWAkqJzwR1TYiK6I
###
get http://localhost:4000/settings/heaterStateHistory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDM3NzMwOCwiZXhwIjoxNzE0MzgwOTA4fQ.Vk9IozjS0fYz13LiE1PX2odbtW0FWAkqJzwR1TYiK6I
###
get http://localhost:4000/settings/stsTokenHistory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDM3NzMwOCwiZXhwIjoxNzE0MzgwOTA4fQ.Vk9IozjS0fYz13LiE1PX2odbtW0FWAkqJzwR1TYiK6I
