get http://localhost:4000/settings/meterResetHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDQyMzU5NCwiZXhwIjoxNzE0NDI3MTk0fQ.SUBul6Gom5kos2T7zF2wHoYTJATUKyl6N4_lqDpBzvE
###
get http://localhost:4000/settings/meterCalibrationHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDQyMzU5NCwiZXhwIjoxNzE0NDI3MTk0fQ.SUBul6Gom5kos2T7zF2wHoYTJATUKyl6N4_lqDpBzvE
###
get http://localhost:4000/settings/meterControlHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDQyMzU5NCwiZXhwIjoxNzE0NDI3MTk0fQ.SUBul6Gom5kos2T7zF2wHoYTJATUKyl6N4_lqDpBzvE
###
get http://localhost:4000/settings/meterStateHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDQyMzU5NCwiZXhwIjoxNzE0NDI3MTk0fQ.SUBul6Gom5kos2T7zF2wHoYTJATUKyl6N4_lqDpBzvE
###
get http://localhost:4000/settings/heaterControlHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDQyMzU5NCwiZXhwIjoxNzE0NDI3MTk0fQ.SUBul6Gom5kos2T7zF2wHoYTJATUKyl6N4_lqDpBzvE
###
get http://localhost:4000/settings/heaterStateHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDQyMzU5NCwiZXhwIjoxNzE0NDI3MTk0fQ.SUBul6Gom5kos2T7zF2wHoYTJATUKyl6N4_lqDpBzvE
###
get http://localhost:4000/settings/stsTokenHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDQyMzU5NCwiZXhwIjoxNzE0NDI3MTk0fQ.SUBul6Gom5kos2T7zF2wHoYTJATUKyl6N4_lqDpBzvE
###
get http://localhost:4000/settings/tokenInformation/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDQ2NDk3MSwiZXhwIjoxNzE0NDY4NTcxfQ.YUM0GibKf2wiybgOg-gOJmuzYN28W6aVzrM0aCje2QQ