post http://localhost:4000/suburb-time-periods 
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxMzc4NjQ5NCwiZXhwIjoxNzEzNzkwMDk0fQ.wxPTLO-SbhPJ_s4NgJlCjngbdU10RsaE1R2chdSrpqw

{
    "suburbs":[
     "Academia" 
    ]
}
###
post http://localhost:4000/search-by-weekly-power 
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxMzc5MTc0MCwiZXhwIjoxNzEzNzk1MzQwfQ.yUu1VGJdNlvB9tutaiv9HAvmUDZ0ZjEKNJfwBD9RDgY

{
    "suburbs":[
     "Academia" 
    ]
}
###
post http://localhost:4000/search-by-monthly-power
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxMzc5NTY4MywiZXhwIjoxNzEzNzk5MjgzfQ.2g6Cf753HRpYlxeqcafQU7lgtnn6JK9T9bZhVK--HFg

{
    "suburbs":[
     "Academia" 
    ]
}

###

