name: Build and Push Docker Image

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t node-web-app .

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: AWS ECR Login
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <ecr-repo-url>

      - name: Build Status Check
        id: build
        run: |
          echo "success=true" >> $GITHUB_ENV
        continue-on-error: true

      - name: Push Docker Image to ECR
        run: |
          if [ "$success" == "true" ]; then
            docker tag node-web-app:latest <ecr-repo-url>:latest
            docker push <ecr-repo-url>:latest
          else
            echo "Build was not successful, skipping ECR push."
          fi